# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer
local   all             all                                     scram-sha-256
host    all             postgres        172.20.0.0/16           scram-sha-256
host    replication     repl_user       172.20.0.0/16           scram-sha-256
host    ppv_db          all             172.20.0.6/32           scram-sha-256
host    ppv_db          all             172.20.0.7/32           scram-sha-256
